sudo: false
dist: trusty
language: node_js
git:
  depth: 3
node_js:
  - "4"
  - "6"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm install -g npm@3; fi
  - "export TRAVIS_COMMIT_MSG=\"`git log --format=%B --no-merges -n 1`\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export TWBS_DO_VALIDATOR=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip sauce\]'; export TWBS_DO_SAUCE=$?; true
  - if [ "$TRAVIS_REPO_SLUG" = twbs-savage/bootstrap ]; then export TWBS_DO_VALIDATOR=0; fi
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 52 1024x768x24 > /dev/null 2>&1 &
  - stty cols 80
  - bundle install --deployment --jobs=3 --retry=3
  - cp grunt/npm-shrinkwrap.json ./
  - npm install
cache:
  directories:
    - node_modules
    - vendor/bundle
    - "$HOME/google-cloud-sdk"
addons:
  apt:
    packages:
      - xvfb